esphome:
  name: twc
  friendly_name: Tesla Wall Connector

esp32:
  board: esp32dev

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Fallback Hotspot"
    password: ""

captive_portal:


logger:
  level: DEBUG

ota:

api:

uart:
  id: twc_uart
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

external_components:
  #- source: github://jnicolson/esphome-twc-controller
      #components: [twc-controller]
  - source: components


sensor:
  - platform: dht
    pin: 18
    temperature:
      name: "Garasje Temperature"
    humidity:
      name: "Garasje Humidity"
    update_interval: 120s
    model: AM2302


twc-controller:
  id: twc
  uart_id: twc_uart
  passive_mode: 1
  min_current: 6
  max_current: 32
  set_current: 6
  twc_id: 0xAB32
  flow_control_pin: 4
  current:
    name: "Charging Current"
  max_allowable_current:
    name: "Maximum Allowable Current"
  total_kwh_delivered:
    name: "Total kWh Delivered"
  serial:
    name: "Serial"
  phase_1_voltage:
    name: "Phase 1 Voltage"
  phase_2_voltage:
    name: "Phase 2 Voltage"
  phase_3_voltage:
    name: "Phase 3 Voltage"
  phase_1_current:
    name: "Phase 1 Current"
  phase_2_current:
    name: "Phase 2 Current"
  phase_3_current:
    name: "Phase 3 Current"
  firmware_version:
    name: "Firmware Version"
  actual_current:
    name: "Actual Current"
  connected_vin:
    name: "Connected VIN"
  state:
    name: "State"
